# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedpullrequest',
            name='pr_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedpullrequest',
            name='target_org',
            field=models.CharField(default='', help_text='GitHub organization name for the target repo (into which this PR will be merged)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedpullrequest',
            name='target_repo',
            field=models.CharField(default='', help_text='GitHub repository name for the target repo (into which this PR will be merged)', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='watchedpullrequest',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='watchedpullrequest',
            name='github_organization_name',
        ),
        migrations.RemoveField(
            model_name='watchedpullrequest',
            name='github_pr_url',
        ),
        migrations.RemoveField(
            model_name='watchedpullrequest',
            name='github_repository_name',
        ),
        migrations.RemoveField(
            model_name='watchedpullrequest',
            name='ref_type',
        ),
        migrations.AlterUniqueTogether(
            name='watchedpullrequest',
            unique_together=set([('target_org', 'target_repo', 'pr_number')]),
        ),
    ]
