# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0002_auto_20170905_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.CharField(db_index=True, help_text='Github organization whose repositories can be watched for PRs. E.g.: open-craft', max_length=200)),
                ('fork', models.CharField(db_index=True, help_text='Github fork name that will be watched for PRs. E.g.: open-craft/edx-platform', max_length=200)),
                ('configuration_source_repo_url', models.URLField(blank=True, help_text='If set, it overrides the default configuration repository', null=True)),
                ('configuration_version', models.CharField(blank=True, help_text='If set, it overrides the default configuration version', max_length=200, null=True)),
                ('configuration_extra_settings', models.TextField(blank=True, default='', help_text='YAML string with extra variables. These take precedence over the others')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='watchedfork',
            unique_together=set([('organization', 'fork')]),
        ),
        migrations.AddField(
            model_name='watchedpullrequest',
            name='watched_fork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pr_watch.WatchedFork'),
        ),
    ]
