# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0004_auto_20171108_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedpullrequest',
            name='watched_fork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_watch.WatchedFork'),
        ),
    ]
