# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0005_auto_20171109_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfork',
            name='configuration_extra_settings',
            field=models.TextField(blank=True, default='', help_text="YAML string with extra variables. These take precedence over the instance's default extra settings, but can be overriden by the PR settings"),
        ),
        migrations.AlterField(
            model_name='watchedfork',
            name='organization',
            field=models.CharField(db_index=True, help_text='Watched GitHub organization. E.g.: open-craft. PRs against the watched fork made by members of this organization will trigger a sandbox build', max_length=200),
        ),
    ]
