# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0006_auto_20171115_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedfork',
            name='openedx_release',
            field=models.CharField(blank=True, help_text='If set, it overrides the the default Open edX release tag', max_length=128, null=True),
        ),
    ]
