# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-24 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0008_update_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfork',
            name='organization',
            field=models.ForeignKey(null=True, help_text='Organization to watch. PRs against the watched fork made by members of this organization will trigger a sandbox build.', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Organization'),
        ),
    ]
