# Generated by Django 2.2.9 on 2020-02-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pr_watch', '0009_organization_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedpullrequest',
            name='watched_fork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pr_watch.WatchedFork'),
        ),
    ]
