# Generated by Django 2.2.12 on 2020-08-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0011_unique_constraints_watched_pr'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedpullrequest',
            unique_together={('github_organization_name', 'github_repository_name', 'branch_name', 'watched_fork', 'github_pr_url')},
        ),
    ]
