# Generated by Django 2.2.12 on 2021-03-15 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_watch', '0013_add_ansible_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfork',
            name='openstack_server_base_image',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON openstack base image selector, e.g. {"name": "focal-20.04-unmodified"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
    ]
