# Generated by Django 2.2.24 on 2021-12-03 11:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import functools
import instance.models.utils
import instance.schemas.static_content_overrides


class Migration(migrations.Migration):

    dependencies = [
        ('grove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groveinstance',
            name='s3_access_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='s3_bucket_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='s3_region',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('AWS_S3_DEFAULT_REGION',), **{}), help_text='The region must support Signature Version 2. See https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region for options. When set empty, the bucket is created in the default region us-east-1.', max_length=50),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='static_content_display',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='Configure `MKTG_URL_LINK_MAP` to display/hide static pages', null=True),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='static_content_overrides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='The final static content overrides data committed by the user for deployment. This should be picked up the appservers launched for this instance.', null=True, validators=[instance.schemas.static_content_overrides.static_content_overrides_schema_validate], verbose_name='Static content overrides JSON'),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='storage_type',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('INSTANCE_STORAGE_TYPE',), **{}), max_length=16),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='swift_openstack_auth_url',
            field=models.URLField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('SWIFT_OPENSTACK_AUTH_URL',), **{})),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='swift_openstack_password',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('SWIFT_OPENSTACK_PASSWORD',), **{}), max_length=64),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='swift_openstack_region',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('SWIFT_OPENSTACK_REGION',), **{}), max_length=16),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='swift_openstack_tenant',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('SWIFT_OPENSTACK_TENANT',), **{}), max_length=32),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='swift_openstack_user',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('SWIFT_OPENSTACK_USER',), **{}), max_length=32),
        ),
        migrations.AddField(
            model_name='groveinstance',
            name='swift_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
