# Generated by Django 2.2.24 on 2022-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grove', '0006_add_mfe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='groveclusterrepository',
            name='git_repo_url',
            field=models.CharField(default='https://gitlab.com/opencraft/dev/grove-development', help_text='Repository URL.', max_length=255),
            preserve_default=False,
        ),
    ]
