# Generated by Django 2.2.24 on 2022-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grove', '0008_auto_20220430_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grovedeployment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Triggered Deployment'), (2, 'Deployed'), (3, 'Cancelled'), (4, 'Failed')], default=0),
        ),
    ]
