# Generated by Django 2.2.24 on 2022-06-03 12:49

from django.db import migrations, models
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('grove', '0009_auto_20220430_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groveinstance',
            name='configuration_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('DEFAULT_CONFIGURATION_VERSION',), **{}), max_length=256),
        ),
    ]
