---
# A simple one-off playbook that allows starting and stopping instance services.
# This is used by Ocim to stop celery workers from inactive appservers to pick
# up tasks.

- hosts: all
  become: yes
  tasks:
    - name: Change state of supervisord managed services
      supervisorctl:
        name:  "{{ services }}"
        state: "{{ supervisord_action }}"
        supervisorctl_path: /edx/bin/supervisorctl
