version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
        environment:
          DEBUG: 'true'
          DEFAULT_FORK: 'open-craft/edx-platform'
          LOAD_BALANCER_FRAGMENT_NAME_PREFIX: 'integration-'
      - image: redis
      - image: mongo:3.2-jessie
      - image: "circleci/mysql:5"
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: True
      - image: circleci/postgres:10.1-alpine
        environment:
          PG_HOST: 127.0.0.1
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    parameters:
        tests_group:
            type: integer
        tests_type:
            type: string
    environment:
        TEST_GROUP: <<parameters.tests_group>>
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 10s
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 10s
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://localhost:3306 -timeout 10s
      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 10s
      - run:
          name: Install Dependencies
          command: |
            sed -i 's/libmysqlclient/default-libmysqlclient/' debian_packages.lst
            make install_system_dependencies
            sudo ln -s /usr/lib/x86_64-linux-gnu/libmysqlclient.so /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
            bin/install-supported-firefox
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade virtualenv
            pip install -r requirements.txt
            pip install -r cleanup_utils/requirements.txt
            npm install
      - run:
          name: Run Consul
          command: |
            echo Running consul agent to connect to the integration consul server
            sudo wget -P /tmp https://releases.hashicorp.com/consul/1.2.1/consul_1.2.1_linux_amd64.zip
            sudo unzip /tmp/consul_1.2.1_linux_amd64.zip -d /usr/local/bin
            mkdir -p /tmp/consul-data
            consul agent -retry-join haproxy-integration.net.opencraft.hosting -data-dir /tmp/consul-data
          background: true
      - save_cache:
          key: dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Create Database
          command: make create_db
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            mkdir -p /tmp/coverage
            make << parameters.tests_type >>
            if [ -e .coverage.* ]; then
                cp -v .coverage.* /tmp/coverage/.
            fi
            if [ -d coverage ]; then
                cp -vR coverage/* /tmp/coverage/.
            fi
          no_output_timeout: 2h
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - persist_to_workspace:
          root: /tmp
          paths:
              - coverage
  coverage:
    docker:
      - image: circleci/python:3.6-stretch-node
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade virtualenv
            sudo apt-get update; sudo apt-get install python2.7-dev
            sudo apt-get install mysql-client
            pip install -r requirements.txt
            pip install -r cleanup_utils/requirements.txt
            sudo apt-get install postgresql-client
            sudo apt-get install unzip
            sudo wget -P /tmp https://releases.hashicorp.com/consul/1.2.1/consul_1.2.1_linux_amd64.zip
            sed -i 's/libmysqlclient/default-libmysqlclient/' debian_packages.lst
            make install_system_dependencies
            npm install
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
              . venv/bin/activate
              coverage combine --append /tmp/workspace/coverage/
              make cov.html
              if [ -e /tmp/workspace/coverage/text/coverage.txt ]; then cat /tmp/workspace/coverage/text/coverage.txt; fi
  cleanup:
    docker:
      - image: circleci/python:3.6-stretch
        environment:
          LOAD_BALANCER_FRAGMENT_NAME_PREFIX: 'integration-'
          DJANGO_SETTINGS_MODULE: 'opencraft.settings'
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt-get install libpython2.7-dev
            pip install -r cleanup_utils/requirements.txt
      - run:
          name: Cleanup
          command: |
            . venv/bin/activate
            make test.integration_cleanup
          no_output_timeout: 20m
          when: always
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          name: quality_migrations_tests
          tests_group: 0
          tests_type: clean test.quality test.migrations_missing
      - build:
          name: python_unit_tests
          tests_group: 0
          tests_type: clean test.unit
      - build:
          name: browser_tests
          tests_group: 0
          tests_type: clean test.browser
      - build:
          name: js_tests
          tests_group: 0
          tests_type: clean test.js
      - build:
          name: integration_tests_group_1
          tests_group: 1
          tests_type: test.integration
          requires:
            - quality_migrations_tests
            - python_unit_tests
            - browser_tests
            - js_tests
      - build:
          name: integration_tests_group_2
          tests_group: 2
          tests_type: test.integration
          requires:
            - quality_migrations_tests
            - python_unit_tests
            - browser_tests
            - js_tests
      - coverage:
          name: coverage
          requires:
            - integration_tests_group_1
            - integration_tests_group_2
  cleanup-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cleanup
