/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericAPIErrorErrors
 */
export interface GenericAPIErrorErrors {
    /**
     * Error code
     * @type {string}
     * @memberof GenericAPIErrorErrors
     */
    code?: string;
    /**
     * Error details
     * @type {string}
     * @memberof GenericAPIErrorErrors
     */
    detail?: string;
}

export function GenericAPIErrorErrorsFromJSON(json: any): GenericAPIErrorErrors {
    return GenericAPIErrorErrorsFromJSONTyped(json, false);
}

export function GenericAPIErrorErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericAPIErrorErrors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
    };
}

export function GenericAPIErrorErrorsToJSON(value?: GenericAPIErrorErrors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'detail': value.detail,
    };
}


