/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceReferenceMinimal
 */
export interface InstanceReferenceMinimal {
    /**
     * 
     * @type {number}
     * @memberof InstanceReferenceMinimal
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof InstanceReferenceMinimal
     */
    readonly apiUrl?: string;
}

export function InstanceReferenceMinimalFromJSON(json: any): InstanceReferenceMinimal {
    return InstanceReferenceMinimalFromJSONTyped(json, false);
}

export function InstanceReferenceMinimalFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceReferenceMinimal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'apiUrl': !exists(json, 'api_url') ? undefined : json['api_url'],
    };
}

export function InstanceReferenceMinimalToJSON(value?: InstanceReferenceMinimal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


