/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoFaviconUpload
 */
export interface LogoFaviconUpload {
    /**
     * 
     * @type {string}
     * @memberof LogoFaviconUpload
     */
    readonly logo?: string;
    /**
     * 
     * @type {string}
     * @memberof LogoFaviconUpload
     */
    readonly favicon?: string;
}

export function LogoFaviconUploadFromJSON(json: any): LogoFaviconUpload {
    return LogoFaviconUploadFromJSONTyped(json, false);
}

export function LogoFaviconUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoFaviconUpload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'favicon': !exists(json, 'favicon') ? undefined : json['favicon'],
    };
}

export function LogoFaviconUploadToJSON(value?: LogoFaviconUpload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


