/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenEdXInstanceDeploymentStatus
 */
export interface OpenEdXInstanceDeploymentStatus {
    /**
     * 
     * @type {string}
     * @memberof OpenEdXInstanceDeploymentStatus
     */
    status: OpenEdXInstanceDeploymentStatusStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof OpenEdXInstanceDeploymentStatus
     */
    undeployedChanges: number;
}

export function OpenEdXInstanceDeploymentStatusFromJSON(json: any): OpenEdXInstanceDeploymentStatus {
    return OpenEdXInstanceDeploymentStatusFromJSONTyped(json, false);
}

export function OpenEdXInstanceDeploymentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenEdXInstanceDeploymentStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'undeployedChanges': json['undeployed_changes'],
    };
}

export function OpenEdXInstanceDeploymentStatusToJSON(value?: OpenEdXInstanceDeploymentStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'undeployed_changes': value.undeployedChanges,
    };
}

/**
* @export
* @enum {string}
*/
export enum OpenEdXInstanceDeploymentStatusStatusEnum {
    NOSTATUS = 'NO_STATUS',
    PREPARINGINSTANCE = 'PREPARING_INSTANCE',
    PENDINGCHANGES = 'PENDING_CHANGES',
    UPTODATE = 'UP_TO_DATE',
    DEPLOYING = 'DEPLOYING'
}


