/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenEdXInstanceDeploymentCreate
 */
export interface OpenEdXInstanceDeploymentCreate {
    /**
     * 
     * @type {number}
     * @memberof OpenEdXInstanceDeploymentCreate
     */
    id: number;
}

export function OpenEdXInstanceDeploymentCreateFromJSON(json: any): OpenEdXInstanceDeploymentCreate {
    return OpenEdXInstanceDeploymentCreateFromJSONTyped(json, false);
}

export function OpenEdXInstanceDeploymentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenEdXInstanceDeploymentCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function OpenEdXInstanceDeploymentCreateToJSON(value?: OpenEdXInstanceDeploymentCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


