/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StaticContentOverrides,
    StaticContentOverridesFromJSON,
    StaticContentOverridesFromJSONTyped,
    StaticContentOverridesToJSON,
    ThemeSchema,
    ThemeSchemaFromJSON,
    ThemeSchemaFromJSONTyped,
    ThemeSchemaToJSON,
} from './';

/**
 * 
 * @export
 * @interface OpenEdXInstanceConfig
 */
export interface OpenEdXInstanceConfig {
    /**
     * 
     * @type {number}
     * @memberof OpenEdXInstanceConfig
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    readonly lmsUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    readonly studioUrl?: string;
    /**
     * The URL students will visit. In the future, you will also have the possibility to use your own domain name.
     * 
     * Example: hogwarts.opencraft.hosting
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    subdomain: string;
    /**
     * The URL students will visit if you are using an external domain.
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    externalDomain?: string | null;
    /**
     * The name of your institution, company or project.
     * 
     * Example: Hogwarts Online Learning
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    instanceName: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    publicContactEmail?: string;
    /**
     * URL to the privacy policy.
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    privacyPolicyUrl?: string;
    /**
     * The advanced theme allows users to pick a lot more details than the regular theme.Setting this flag will enable the more complex theme editor.
     * @type {boolean}
     * @memberof OpenEdXInstanceConfig
     */
    useAdvancedTheme?: boolean;
    /**
     * 
     * @type {ThemeSchema}
     * @memberof OpenEdXInstanceConfig
     */
    draftThemeConfig?: ThemeSchema;
    /**
     * Your branding to be displayed throughout your instance. It should be 48px tall. If unset, OpenCraft's logo will be used.
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    readonly logo?: string;
    /**
     * This is used as the browser tab icon for your instance's pages. If unset, OpenCraft's icon will be used.
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    readonly favicon?: string;
    /**
     * This is used as the cover image for the hero section in the instance LMS home page.
     * @type {string}
     * @memberof OpenEdXInstanceConfig
     */
    readonly heroCoverImage?: string | null;
    /**
     * 
     * @type {StaticContentOverrides}
     * @memberof OpenEdXInstanceConfig
     */
    draftStaticContentOverrides?: StaticContentOverrides;
}

export function OpenEdXInstanceConfigFromJSON(json: any): OpenEdXInstanceConfig {
    return OpenEdXInstanceConfigFromJSONTyped(json, false);
}

export function OpenEdXInstanceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenEdXInstanceConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lmsUrl': !exists(json, 'lms_url') ? undefined : json['lms_url'],
        'studioUrl': !exists(json, 'studio_url') ? undefined : json['studio_url'],
        'subdomain': json['subdomain'],
        'externalDomain': !exists(json, 'external_domain') ? undefined : json['external_domain'],
        'instanceName': json['instance_name'],
        'publicContactEmail': !exists(json, 'public_contact_email') ? undefined : json['public_contact_email'],
        'privacyPolicyUrl': !exists(json, 'privacy_policy_url') ? undefined : json['privacy_policy_url'],
        'useAdvancedTheme': !exists(json, 'use_advanced_theme') ? undefined : json['use_advanced_theme'],
        'draftThemeConfig': !exists(json, 'draft_theme_config') ? undefined : ThemeSchemaFromJSON(json['draft_theme_config']),
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'favicon': !exists(json, 'favicon') ? undefined : json['favicon'],
        'heroCoverImage': !exists(json, 'hero_cover_image') ? undefined : json['hero_cover_image'],
        'draftStaticContentOverrides': !exists(json, 'draft_static_content_overrides') ? undefined : StaticContentOverridesFromJSON(json['draft_static_content_overrides']),
    };
}

export function OpenEdXInstanceConfigToJSON(value?: OpenEdXInstanceConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subdomain': value.subdomain,
        'external_domain': value.externalDomain,
        'instance_name': value.instanceName,
        'public_contact_email': value.publicContactEmail,
        'privacy_policy_url': value.privacyPolicyUrl,
        'use_advanced_theme': value.useAdvancedTheme,
        'draft_theme_config': ThemeSchemaToJSON(value.draftThemeConfig),
        'draft_static_content_overrides': StaticContentOverridesToJSON(value.draftStaticContentOverrides),
    };
}


