/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpawnAppServer
 */
export interface SpawnAppServer {
    /**
     * 
     * @type {number}
     * @memberof SpawnAppServer
     */
    instanceId: number;
}

export function SpawnAppServerFromJSON(json: any): SpawnAppServer {
    return SpawnAppServerFromJSONTyped(json, false);
}

export function SpawnAppServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpawnAppServer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceId': json['instance_id'],
    };
}

export function SpawnAppServerToJSON(value?: SpawnAppServer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance_id': value.instanceId,
    };
}


