/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaticContentOverrides
 */
export interface StaticContentOverrides {
    /**
     * 
     * @type {number}
     * @memberof StaticContentOverrides
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateAboutHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateAboutContent?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateContactHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateContactContent?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateDonateHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateDonateContent?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateTosHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateTosContent?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateHonorHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplateHonorContent?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplatePrivacyHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    staticTemplatesPrivacyContent?: string;
    /**
     * 
     * @type {string}
     * @memberof StaticContentOverrides
     */
    homepageOverlayHtml?: string;
}

export function StaticContentOverridesFromJSON(json: any): StaticContentOverrides {
    return StaticContentOverridesFromJSONTyped(json, false);
}

export function StaticContentOverridesFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaticContentOverrides {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'staticTemplateAboutHeader': !exists(json, 'static_template_about_header') ? undefined : json['static_template_about_header'],
        'staticTemplateAboutContent': !exists(json, 'static_template_about_content') ? undefined : json['static_template_about_content'],
        'staticTemplateContactHeader': !exists(json, 'static_template_contact_header') ? undefined : json['static_template_contact_header'],
        'staticTemplateContactContent': !exists(json, 'static_template_contact_content') ? undefined : json['static_template_contact_content'],
        'staticTemplateDonateHeader': !exists(json, 'static_template_donate_header') ? undefined : json['static_template_donate_header'],
        'staticTemplateDonateContent': !exists(json, 'static_template_donate_content') ? undefined : json['static_template_donate_content'],
        'staticTemplateTosHeader': !exists(json, 'static_template_tos_header') ? undefined : json['static_template_tos_header'],
        'staticTemplateTosContent': !exists(json, 'static_template_tos_content') ? undefined : json['static_template_tos_content'],
        'staticTemplateHonorHeader': !exists(json, 'static_template_honor_header') ? undefined : json['static_template_honor_header'],
        'staticTemplateHonorContent': !exists(json, 'static_template_honor_content') ? undefined : json['static_template_honor_content'],
        'staticTemplatePrivacyHeader': !exists(json, 'static_template_privacy_header') ? undefined : json['static_template_privacy_header'],
        'staticTemplatesPrivacyContent': !exists(json, 'static_templates_privacy_content') ? undefined : json['static_templates_privacy_content'],
        'homepageOverlayHtml': !exists(json, 'homepage_overlay_html') ? undefined : json['homepage_overlay_html'],
    };
}

export function StaticContentOverridesToJSON(value?: StaticContentOverrides | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'static_template_about_header': value.staticTemplateAboutHeader,
        'static_template_about_content': value.staticTemplateAboutContent,
        'static_template_contact_header': value.staticTemplateContactHeader,
        'static_template_contact_content': value.staticTemplateContactContent,
        'static_template_donate_header': value.staticTemplateDonateHeader,
        'static_template_donate_content': value.staticTemplateDonateContent,
        'static_template_tos_header': value.staticTemplateTosHeader,
        'static_template_tos_content': value.staticTemplateTosContent,
        'static_template_honor_header': value.staticTemplateHonorHeader,
        'static_template_honor_content': value.staticTemplateHonorContent,
        'static_template_privacy_header': value.staticTemplatePrivacyHeader,
        'static_templates_privacy_content': value.staticTemplatesPrivacyContent,
        'homepage_overlay_html': value.homepageOverlayHtml,
    };
}


