/* tslint:disable */
/* eslint-disable */
/**
 * OpenCraft Instance Manager
 * API for OpenCraft Instance Manager
 *
 * The version of the OpenAPI document: api
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeSchemaSerializerGenerator
 */
export interface ThemeSchemaSerializerGenerator {
    /**
     * 
     * @type {number}
     * @memberof ThemeSchemaSerializerGenerator
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    mainColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    linkColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    headerBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    footerBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    footerColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    footerLinkColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnPrimaryBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnPrimaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnPrimaryBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnPrimaryHoverBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnPrimaryHoverColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnPrimaryHoverBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSecondaryBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSecondaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSecondaryBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSecondaryHoverBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSecondaryHoverColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSecondaryHoverBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    accentColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    homePageHeroTitleColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    homePageHeroSubtitleColor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeSchemaSerializerGenerator
     */
    customizeSignInBtn?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSignInBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSignInColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSignInBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSignInHoverBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSignInHoverColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnSignInHoverBorderColor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeSchemaSerializerGenerator
     */
    customizeRegisterBtn?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnRegisterBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnRegisterColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnRegisterBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnRegisterHoverBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnRegisterHoverColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnRegisterHoverBorderColor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeSchemaSerializerGenerator
     */
    customizeLogistrationActionBtn?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnLogistrationBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnLogistrationColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnLogistrationBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnLogistrationHoverBg?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnLogistrationHoverColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    btnLogistrationHoverBorderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    loginRegisterHeaderColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    mainNavColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    mainNavLinkColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    mainNavItemBorderBottomColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    mainNavItemHoverBorderBottomColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    userDropdownColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    wrapperPreviewMenuColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    courseNavMenuBorderBottomColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    accountSettingsNavBorderBottomColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeSchemaSerializerGenerator
     */
    accountSettingsNavHoverBorderBottomColor?: string;
}

export function ThemeSchemaSerializerGeneratorFromJSON(json: any): ThemeSchemaSerializerGenerator {
    return ThemeSchemaSerializerGeneratorFromJSONTyped(json, false);
}

export function ThemeSchemaSerializerGeneratorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeSchemaSerializerGenerator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'mainColor': !exists(json, 'main-color') ? undefined : json['main-color'],
        'linkColor': !exists(json, 'link-color') ? undefined : json['link-color'],
        'headerBg': !exists(json, 'header-bg') ? undefined : json['header-bg'],
        'footerBg': !exists(json, 'footer-bg') ? undefined : json['footer-bg'],
        'footerColor': !exists(json, 'footer-color') ? undefined : json['footer-color'],
        'footerLinkColor': !exists(json, 'footer-link-color') ? undefined : json['footer-link-color'],
        'btnPrimaryBg': !exists(json, 'btn-primary-bg') ? undefined : json['btn-primary-bg'],
        'btnPrimaryColor': !exists(json, 'btn-primary-color') ? undefined : json['btn-primary-color'],
        'btnPrimaryBorderColor': !exists(json, 'btn-primary-border-color') ? undefined : json['btn-primary-border-color'],
        'btnPrimaryHoverBg': !exists(json, 'btn-primary-hover-bg') ? undefined : json['btn-primary-hover-bg'],
        'btnPrimaryHoverColor': !exists(json, 'btn-primary-hover-color') ? undefined : json['btn-primary-hover-color'],
        'btnPrimaryHoverBorderColor': !exists(json, 'btn-primary-hover-border-color') ? undefined : json['btn-primary-hover-border-color'],
        'btnSecondaryBg': !exists(json, 'btn-secondary-bg') ? undefined : json['btn-secondary-bg'],
        'btnSecondaryColor': !exists(json, 'btn-secondary-color') ? undefined : json['btn-secondary-color'],
        'btnSecondaryBorderColor': !exists(json, 'btn-secondary-border-color') ? undefined : json['btn-secondary-border-color'],
        'btnSecondaryHoverBg': !exists(json, 'btn-secondary-hover-bg') ? undefined : json['btn-secondary-hover-bg'],
        'btnSecondaryHoverColor': !exists(json, 'btn-secondary-hover-color') ? undefined : json['btn-secondary-hover-color'],
        'btnSecondaryHoverBorderColor': !exists(json, 'btn-secondary-hover-border-color') ? undefined : json['btn-secondary-hover-border-color'],
        'accentColor': !exists(json, 'accent-color') ? undefined : json['accent-color'],
        'homePageHeroTitleColor': !exists(json, 'home-page-hero-title-color') ? undefined : json['home-page-hero-title-color'],
        'homePageHeroSubtitleColor': !exists(json, 'home-page-hero-subtitle-color') ? undefined : json['home-page-hero-subtitle-color'],
        'customizeSignInBtn': !exists(json, 'customize-sign-in-btn') ? undefined : json['customize-sign-in-btn'],
        'btnSignInBg': !exists(json, 'btn-sign-in-bg') ? undefined : json['btn-sign-in-bg'],
        'btnSignInColor': !exists(json, 'btn-sign-in-color') ? undefined : json['btn-sign-in-color'],
        'btnSignInBorderColor': !exists(json, 'btn-sign-in-border-color') ? undefined : json['btn-sign-in-border-color'],
        'btnSignInHoverBg': !exists(json, 'btn-sign-in-hover-bg') ? undefined : json['btn-sign-in-hover-bg'],
        'btnSignInHoverColor': !exists(json, 'btn-sign-in-hover-color') ? undefined : json['btn-sign-in-hover-color'],
        'btnSignInHoverBorderColor': !exists(json, 'btn-sign-in-hover-border-color') ? undefined : json['btn-sign-in-hover-border-color'],
        'customizeRegisterBtn': !exists(json, 'customize-register-btn') ? undefined : json['customize-register-btn'],
        'btnRegisterBg': !exists(json, 'btn-register-bg') ? undefined : json['btn-register-bg'],
        'btnRegisterColor': !exists(json, 'btn-register-color') ? undefined : json['btn-register-color'],
        'btnRegisterBorderColor': !exists(json, 'btn-register-border-color') ? undefined : json['btn-register-border-color'],
        'btnRegisterHoverBg': !exists(json, 'btn-register-hover-bg') ? undefined : json['btn-register-hover-bg'],
        'btnRegisterHoverColor': !exists(json, 'btn-register-hover-color') ? undefined : json['btn-register-hover-color'],
        'btnRegisterHoverBorderColor': !exists(json, 'btn-register-hover-border-color') ? undefined : json['btn-register-hover-border-color'],
        'customizeLogistrationActionBtn': !exists(json, 'customize-logistration-action-btn') ? undefined : json['customize-logistration-action-btn'],
        'btnLogistrationBg': !exists(json, 'btn-logistration-bg') ? undefined : json['btn-logistration-bg'],
        'btnLogistrationColor': !exists(json, 'btn-logistration-color') ? undefined : json['btn-logistration-color'],
        'btnLogistrationBorderColor': !exists(json, 'btn-logistration-border-color') ? undefined : json['btn-logistration-border-color'],
        'btnLogistrationHoverBg': !exists(json, 'btn-logistration-hover-bg') ? undefined : json['btn-logistration-hover-bg'],
        'btnLogistrationHoverColor': !exists(json, 'btn-logistration-hover-color') ? undefined : json['btn-logistration-hover-color'],
        'btnLogistrationHoverBorderColor': !exists(json, 'btn-logistration-hover-border-color') ? undefined : json['btn-logistration-hover-border-color'],
        'loginRegisterHeaderColor': !exists(json, 'login-register-header-color') ? undefined : json['login-register-header-color'],
        'mainNavColor': !exists(json, 'main-nav-color') ? undefined : json['main-nav-color'],
        'mainNavLinkColor': !exists(json, 'main-nav-link-color') ? undefined : json['main-nav-link-color'],
        'mainNavItemBorderBottomColor': !exists(json, 'main-nav-item-border-bottom-color') ? undefined : json['main-nav-item-border-bottom-color'],
        'mainNavItemHoverBorderBottomColor': !exists(json, 'main-nav-item-hover-border-bottom-color') ? undefined : json['main-nav-item-hover-border-bottom-color'],
        'userDropdownColor': !exists(json, 'user-dropdown-color') ? undefined : json['user-dropdown-color'],
        'wrapperPreviewMenuColor': !exists(json, 'wrapper-preview-menu-color') ? undefined : json['wrapper-preview-menu-color'],
        'courseNavMenuBorderBottomColor': !exists(json, 'course-nav-menu-border-bottom-color') ? undefined : json['course-nav-menu-border-bottom-color'],
        'accountSettingsNavBorderBottomColor': !exists(json, 'account-settings-nav-border-bottom-color') ? undefined : json['account-settings-nav-border-bottom-color'],
        'accountSettingsNavHoverBorderBottomColor': !exists(json, 'account-settings-nav-hover-border-bottom-color') ? undefined : json['account-settings-nav-hover-border-bottom-color'],
    };
}

export function ThemeSchemaSerializerGeneratorToJSON(value?: ThemeSchemaSerializerGenerator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'main-color': value.mainColor,
        'link-color': value.linkColor,
        'header-bg': value.headerBg,
        'footer-bg': value.footerBg,
        'footer-color': value.footerColor,
        'footer-link-color': value.footerLinkColor,
        'btn-primary-bg': value.btnPrimaryBg,
        'btn-primary-color': value.btnPrimaryColor,
        'btn-primary-border-color': value.btnPrimaryBorderColor,
        'btn-primary-hover-bg': value.btnPrimaryHoverBg,
        'btn-primary-hover-color': value.btnPrimaryHoverColor,
        'btn-primary-hover-border-color': value.btnPrimaryHoverBorderColor,
        'btn-secondary-bg': value.btnSecondaryBg,
        'btn-secondary-color': value.btnSecondaryColor,
        'btn-secondary-border-color': value.btnSecondaryBorderColor,
        'btn-secondary-hover-bg': value.btnSecondaryHoverBg,
        'btn-secondary-hover-color': value.btnSecondaryHoverColor,
        'btn-secondary-hover-border-color': value.btnSecondaryHoverBorderColor,
        'accent-color': value.accentColor,
        'home-page-hero-title-color': value.homePageHeroTitleColor,
        'home-page-hero-subtitle-color': value.homePageHeroSubtitleColor,
        'customize-sign-in-btn': value.customizeSignInBtn,
        'btn-sign-in-bg': value.btnSignInBg,
        'btn-sign-in-color': value.btnSignInColor,
        'btn-sign-in-border-color': value.btnSignInBorderColor,
        'btn-sign-in-hover-bg': value.btnSignInHoverBg,
        'btn-sign-in-hover-color': value.btnSignInHoverColor,
        'btn-sign-in-hover-border-color': value.btnSignInHoverBorderColor,
        'customize-register-btn': value.customizeRegisterBtn,
        'btn-register-bg': value.btnRegisterBg,
        'btn-register-color': value.btnRegisterColor,
        'btn-register-border-color': value.btnRegisterBorderColor,
        'btn-register-hover-bg': value.btnRegisterHoverBg,
        'btn-register-hover-color': value.btnRegisterHoverColor,
        'btn-register-hover-border-color': value.btnRegisterHoverBorderColor,
        'customize-logistration-action-btn': value.customizeLogistrationActionBtn,
        'btn-logistration-bg': value.btnLogistrationBg,
        'btn-logistration-color': value.btnLogistrationColor,
        'btn-logistration-border-color': value.btnLogistrationBorderColor,
        'btn-logistration-hover-bg': value.btnLogistrationHoverBg,
        'btn-logistration-hover-color': value.btnLogistrationHoverColor,
        'btn-logistration-hover-border-color': value.btnLogistrationHoverBorderColor,
        'login-register-header-color': value.loginRegisterHeaderColor,
        'main-nav-color': value.mainNavColor,
        'main-nav-link-color': value.mainNavLinkColor,
        'main-nav-item-border-bottom-color': value.mainNavItemBorderBottomColor,
        'main-nav-item-hover-border-bottom-color': value.mainNavItemHoverBorderBottomColor,
        'user-dropdown-color': value.userDropdownColor,
        'wrapper-preview-menu-color': value.wrapperPreviewMenuColor,
        'course-nav-menu-border-bottom-color': value.courseNavMenuBorderBottomColor,
        'account-settings-nav-border-bottom-color': value.accountSettingsNavBorderBottomColor,
        'account-settings-nav-hover-border-bottom-color': value.accountSettingsNavHoverBorderBottomColor,
    };
}


