# Generated by Django 2.2.12 on 2021-05-03 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import marketing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the email template. It can be used as an identifier for emails. Must be unique.', max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Template for the subject of email', max_length=256)),
                ('html_body', models.TextField(help_text='Template for the html body of the email.')),
                ('plaintext_body', models.TextField(help_text='Template for the text body of the email.')),
                ('is_active', models.BooleanField(default=False, help_text='If the email is active or not. Emails will be sent for active templates only.')),
                ('send_after_days', models.IntegerField(help_text='Number of days after instance activation the email will be sent', validators=[django.core.validators.MinValueValidator(1), marketing.models.validate_send_after_days_max_value])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_followup', models.BooleanField(default=True, help_text='Should the user receive followup emails?')),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime when first appserver became active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.TextField()),
                ('email_html_body', models.TextField()),
                ('email_plaintext_body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.EmailTemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
