- name: Install Python 2 on target machine
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - raw: sudo apt-get update -qq && sudo apt-get install -qq python

- name: Deploy the OpenCraft Instance Manager
  hosts: all
  become: true
  roles:
    - name: common-server
      COMMON_SERVER_NO_BACKUPS: true    # The instance manager VM is stateless
      UNATTENED_UPGRADES_ERRORS_RELAY_TO: "{{ inventory_hostname }}"
    - name: forward-server-mail
      FORWARD_MAIL_MYDOMAIN: "{{ inventory_hostname }}"
      when: vagrant_mode is undefined or not vagrant_mode
    - name: geerlingguy.nginx
      nginx_remove_default_vhost: true
      when: vagrant_mode is undefined or not vagrant_mode
    - opencraft
    - pmbauer.tarsnap
    - filebeat
