# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 12:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0051_auto_20160530_1229'),
        ('registration', '0002_timestampedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instance.OpenEdXInstance'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='subdomain',
            field=models.CharField(error_messages={'blacklisted': 'This domain name is not publicly available.', 'unique': 'This domain is already taken.'}, help_text='The URL students will visit. In the future, you will also have the possibility to use your own domain name.\n\nExample: hogwarts.opencraft.hosting', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'The subdomain name must at least have 3 characters.'), django.core.validators.RegexValidator('^[\\w.-]+$', "Please include only letters, numbers, '_', '-' and '.'"), registration.models.validate_available_subdomain], verbose_name='domain name'),
        ),
    ]
