# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160530_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='subscribe_to_updates',
            field=models.BooleanField(default=False, help_text='I want OpenCraft to keep me updated about the progress of the beta test, and occasionally send me an email about it.'),
        ),
    ]
