# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 15:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_subscribe_to_updates_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='subdomain',
            field=models.CharField(error_messages={'blacklisted': 'This domain name is not publicly available.', 'unique': 'This domain is already taken.'}, help_text='The URL students will visit. In the future, you will also have the possibility to use your own domain name.\n\nExample: hogwarts.opencraft.hosting', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'The subdomain name must at least have 3 characters.'), django.core.validators.RegexValidator('^[a-zA-Z0-9](?:[a-zA-Z0-9\\-]{1,63}[a-zA-Z0-9])$', 'Please include only letters (case-insensitive), numbers, and hyphens. Cannot start or end with a hyphen.'), registration.models.validate_available_subdomain], verbose_name='domain name'),
        ),
    ]
