# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_subscribe_to_updates_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='bg_color_1',
            field=models.CharField(default='126f9a', help_text='Used as the main filler color for buttons, background, etc.', max_length=6, verbose_name='Primary background color'),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='bg_color_2',
            field=models.CharField(default='c2387d', help_text='Used as the secondary filler color for buttons, background, etc.', max_length=6, verbose_name='Secondary background color'),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='favicon',
            field=models.ImageField(help_text="This is used as the browser tab icon for your instance's pages.", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='link_color',
            field=models.CharField(default='0075b4', help_text='This is used as the color for clickable links on your instance.', max_length=6),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='logo',
            field=models.ImageField(help_text='Your branding to be displayed throughout your instance.', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='main_color',
            field=models.CharField(default='333333', help_text='This is used as the primary color in your theme palette.', max_length=6),
        ),
    ]
