# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_subscribe_to_updates_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='favicon',
            field=models.ImageField(default='opencraft_favicon.ico', help_text="This is used as the browser tab icon for your instance's pages. If unset, OpenCraft's icon will be used.", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='link_color',
            field=models.CharField(default='#126f9a', help_text='This is used as the color for clickable links on your instance.', max_length=7),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='logo',
            field=models.ImageField(default='opencraft_logo_small.png', help_text="Your branding to be displayed throughout your instance. It should be 48px tall. If unset, OpenCraft's logo will be used.", null=True, upload_to='', validators=[registration.models.validate_logo_height]),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='main_color',
            field=models.CharField(default='#126f9a', help_text='This is used as the primary color in your theme palette. It is used as filler for buttons.', max_length=7),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='footer_bg_color',
            field=models.CharField(default='#ffffff', help_text='Used as the background color for the footer.', max_length=7, verbose_name='Footer background color'),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', help_text='Used as the background color for the top bar.', max_length=7, verbose_name='Header background color'),
        ),
    ]
