# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20171003_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='bg_color_1',
            field=models.CharField(default='126f9a', help_text='Used as the main filler color for buttons, background, etc.', max_length=7, verbose_name='Primary background color'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='bg_color_2',
            field=models.CharField(default='c2387d', help_text='Used as the secondary filler color for buttons, background, etc.', max_length=7, verbose_name='Secondary background color'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='link_color',
            field=models.CharField(default='0075b4', help_text='This is used as the color for clickable links on your instance.', max_length=7),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='main_color',
            field=models.CharField(default='333333', help_text='This is used as the primary color in your theme palette.', max_length=7),
        ),
    ]
