# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_add_design_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='favicon',
            field=models.ImageField(default='opencraft_favicon.ico', help_text="This is used as the browser tab icon for your instance's pages.", null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='logo',
            field=models.ImageField(default='opencraft_logo_small.png', help_text='Your branding to be displayed throughout your instance.', null=True, upload_to=''),
        ),
    ]
