# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_default_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betatestapplication',
            name='bg_color_1',
        ),
        migrations.RemoveField(
            model_name='betatestapplication',
            name='bg_color_2',
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='footer_bg_color',
            field=models.CharField(default='#000000', help_text='Used as the background color for the footer', max_length=7, verbose_name='Footer background color'),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='header_bg_color',
            field=models.CharField(default='#000000', help_text='Used as the background color for the top bar', max_length=7, verbose_name='Header background color'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='link_color',
            field=models.CharField(default='#126f9a', help_text='This is used as the color for clickable links on your instance.', max_length=7),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='main_color',
            field=models.CharField(default='#126f9a', help_text='This is used as the primary color in your theme palette. It is used as filler for buttons.', max_length=7),
        ),
    ]
