# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171020_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='footer_bg_color',
            field=models.CharField(default='#ffffff', help_text='Used as the background color for the footer', max_length=7, verbose_name='Footer background color'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', help_text='Used as the background color for the top bar', max_length=7, verbose_name='Header background color'),
        ),
    ]
