# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_fix_invalid_domain_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='project_description',
            field=models.TextField(blank=True, default='', help_text='What are you going to use the instance for? What are your expectations?', verbose_name='your project'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='subscribe_to_updates',
            field=models.BooleanField(default=False, help_text='I want OpenCraft to keep me updated about important news, tips, and new features, and occasionally send me an email about it.'),
        ),
    ]
