# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180309_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='footer_bg_color',
            field=models.CharField(default='#ffffff', help_text='Used as the background color for the footer.', max_length=7, validators=[registration.models.validate_color], verbose_name='Footer background color'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', help_text='Used as the background color for the top bar.', max_length=7, validators=[registration.models.validate_color], verbose_name='Header background color'),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='link_color',
            field=models.CharField(default='#126f9a', help_text='This is used as the color for clickable links on your instance.', max_length=7, validators=[registration.models.validate_color]),
        ),
        migrations.AlterField(
            model_name='betatestapplication',
            name='main_color',
            field=models.CharField(default='#126f9a', help_text='This is used as the primary color in your theme palette. It is used as filler for buttons.', max_length=7, validators=[registration.models.validate_color]),
        ),
    ]
