# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_validate_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='accepted_privacy_policy',
            field=models.DateTimeField(blank=True, help_text='Date the privacy policy was accepted.', null=True),
        ),
    ]
