# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_validate_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='accepted_privacy_policy',
            field=models.DateTimeField(help_text='Date the user accepted the privacy policy.', null=True, verbose_name='Accept privacy policy'),
        ),
    ]
