# Generated by Django 2.2.6 on 2019-11-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_betatestapplication_privacy_policy_url'),
        # Make sure that data from the removed fields has been copied over before
        # they are removed from here.
        ('userprofile', '0005_move_privacy_policy_subscribe_updates_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betatestapplication',
            name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='betatestapplication',
            name='subscribe_to_updates',
        ),
    ]
