# Generated by Django 2.2.6 on 2019-11-13 12:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import instance.schemas.theming


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0012_auto_20191112_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='draft_theme_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 help_text='The theme configuration data currently '
                                                                           'being edited by the user. When finalised '
                                                                           'it willbe copied over to the final theme '
                                                                           'config which will then be deployed to the '
                                                                           'next appserverthat is launched.',
                                                                 null=True,
                                                                 validators=[
                                                                     instance.schemas.theming.theme_schema_validate
                                                                 ],
                                                                 verbose_name='Draft Theme Configuration JSON'),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='use_advanced_theme',
            field=models.BooleanField(default=False,
                                      help_text='The advanced theme allows users to pick a lot more details than the '
                                                'regular theme.Setting this flag will enable the more complex theme '
                                                'editor.'),
        ),
    ]
