# Generated by Django 2.2.6 on 2019-11-13 13:05

from django.db import migrations


def move_separate_theme_fields_to_json(apps, schema_editor):
    BetaTestApplication = apps.get_model('registration', 'BetaTestApplication')
    for application in BetaTestApplication.objects.all():
        draft_theme_config = {
            'version': 0,
            'main_color': application.main_color,
            'link_color': application.link_color,
            'header_bg_color': application.header_bg_color,
            'footer_bg_color': application.footer_bg_color,
            'logo': application.logo.url,
            'favicon': application.favicon.url,
        }
        application.draft_theme_config = draft_theme_config
        application.save()


def move_json_to_separate_theme_fields(apps, schema_editor):
    BetaTestApplication = apps.get_model('registration', 'BetaTestApplication')
    for application in BetaTestApplication.objects.all():
        theme_config = application.draft_theme_config
        application.main_color = theme_config['main_color']
        application.link_color = theme_config['link_color']
        application.header_bg_color = theme_config['header_bg_color']
        application.footer_bg_color = theme_config['footer_bg_color']
        application.logo = theme_config['logo']
        application.favicon = theme_config['favicon']
        application.save()


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0013_auto_20191113_1240'),
    ]

    operations = [
        migrations.RunPython(
            move_separate_theme_fields_to_json,
            move_json_to_separate_theme_fields,
        )
    ]
