# Generated by Django 2.2.6 on 2020-02-11 16:34

import django.core.validators
from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_move_theme_config_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='external_domain',
            field=models.CharField(blank=True, error_messages={'blacklisted': 'This domain name is not publicly available.', 'unique': 'This domain is already taken.'}, help_text='The URL students will visit if you are using an external domain.', max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'The subdomain name must at least have 3 characters.'), django.core.validators.MaxLengthValidator(250, 'The subdomain name can have at most have 250 characters.'), django.core.validators.RegexValidator('^([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}$', 'Please choose a domain name that you already know and own, containing lower-case letters, numbers, dots, and hyphens. Cannot start or end with a hyphen.'), registration.models.validate_available_subdomain], verbose_name='external domain name'),
        ),
    ]
