# Generated by Django 2.2.10 on 2020-03-25 14:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import instance.schemas.static_content_overrides


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_betatestapplication_external_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='draft_static_content_overrides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='The static content overrides data currently being edited by the user. When finalised, it will be copied over to the final static content overrides which will then be deployed to the next appserver that is launched', null=True, validators=[instance.schemas.static_content_overrides.static_content_overrides_schema_validate], verbose_name='Draft static content overrides JSON'),
        ),
    ]
