# Generated by Django 2.2.10 on 2020-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_betatestapplication_draft_static_content_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='hero_cover_image',
            field=models.ImageField(blank=True, default=None, help_text='This is used as the cover image for the hero section in the instance LMS home page.', null=True, upload_to=''),
        ),
    ]
