# Generated by Django 2.2.12 on 2020-10-09 06:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_0018_hardcode_basedomain_and_add_error_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='configuration_display_static_pages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='Configure `MKTG_URL_LINK_MAP` to display/hide static pages', null=True),
        ),
    ]
