# Generated by Django 2.2.12 on 2021-02-05 11:11

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_betatestapplication_configuration_display_static_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='dns_configuration_state',
            field=models.CharField(choices=[('verified', 'External domain DNS configured'), ('pending', 'External domain config verification pending'), ('failed', 'External domain DNS not configured'), ('not_required', 'No external domain set')], default=registration.models.DNSConfigState('No external domain set'), help_text='State of DNS config verfication for external_domain', max_length=15),
        ),
    ]
