# Generated by Django 2.2.23 on 2021-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_betatestapplication_dns_configuration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='betatestapplication',
            name='footer_logo_image',
            field=models.ImageField(blank=True, default='', help_text="If set, it overrides the source for the footer logo image. By default, the 'Powered by OpenEdX' logo is used.", null=True, upload_to='', verbose_name='Footer Logo Image'),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='footer_logo_url',
            field=models.URLField(blank=True, default='', help_text='If set, overrides the link destination for the footer logo. By default, it links to the OpenEdX website.', verbose_name='Footer Logo Link'),
        ),
    ]
