# Generated by Django 2.2.24 on 2022-01-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_add_footer_logo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatestapplication',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grove.GroveInstance'),
        ),
    ]
