# Generated by Django 2.2.24 on 2022-05-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('registration', '0022_auto_20220115_1250'), ('registration', '0023_auto_20220303_0612')]

    dependencies = [
        ('registration', '0021_add_footer_logo_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betatestapplication',
            name='instance',
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='instance_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='instance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
