# Generated by Django 2.2.24 on 2022-03-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registration', '0022_auto_20220115_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betatestapplication',
            name='instance',
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='instance_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betatestapplication',
            name='instance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
