# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0051_auto_20160530_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelicAvailabilityMonitor',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_availability_monitors', to='instance.OpenEdXInstance')),
            ],
        ),
    ]
