# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0052_availability_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='external_lms_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='external_lms_preview_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='external_studio_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
