# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_internal_domains(apps, schema_editor):
    """
    Combine sub_domain and base_domain fields into a single internal_lms_domain field.
    Also generate and store internal_lms_preview_domain and internal_studio_domain fields,
    which are generated by prepending 'preview-' and 'studio-' to the LMS domain.
    These were the hardcoded values for preview/studio domain prefixes at the time this migration
    was created, but they will be configurable in the future.
    """
    Instance = apps.get_model("instance", "OpenEdXInstance")
    for instance in Instance.objects.all():
        instance.internal_lms_domain = '{0.sub_domain}.{0.base_domain}'.format(instance)
        instance.internal_lms_preview_domain = 'preview-{0.sub_domain}.{0.base_domain}'.format(instance)
        instance.internal_studio_domain = 'studio-{0.sub_domain}.{0.base_domain}'.format(instance)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0053_add_external_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='internal_lms_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='internal_lms_preview_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='internal_studio_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(migrate_internal_domains, reverse_code=migrations.RunPython.noop),
    ]
