# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0054_add_internal_domain_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='internal_lms_domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='internal_lms_preview_domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='internal_studio_domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='openedxinstance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='base_domain',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='sub_domain',
        ),
    ]
