# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0055_remove_subdomain_basedomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancereference',
            options={'ordering': ['-created'], 'permissions': (('manage_all', 'Can manage all instances.'),)},
        ),
    ]
