# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 14:48
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0056_auto_20160609_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='github_admin_organizations',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[], help_text='A list of Github organizations; the members of the "Owners" team in these organizations be given SSH admin access to this instance\'s VMs.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='github_admin_users',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[], help_text="A list of Github users who will be given SSH admin access to this instance's VMs.", max_length=256),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='github_admin_organizations',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[], help_text='A list of Github organizations; the members of the "Owners" team in these organizations be given SSH admin access to this instance\'s VMs.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='github_admin_users',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[], help_text="A list of Github users who will be given SSH admin access to this instance's VMs.", max_length=256),
        ),
    ]
