# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 14:50
from __future__ import unicode_literals

from django.db import migrations


def _org_name_to_org_list(instance):
    """Convert the old org name field to a single-item list for a single instance."""
    if instance.github_admin_organization_name:
        instance.github_admin_organizations = [instance.github_admin_organization_name]
        instance.save()


def _org_list_to_org_name(instance):
    """Convert to convert the org list back to the old org name field by picking the first item."""
    if instance.github_admin_organizations:
        instance.github_admin_organization_name = instance.github_admin_organizations[0]
        instance.save()


def _process_instances(apps, schema_editor, callback):
    """Apply the given callback to all OpenEdXAppServer and OpenEdXInstance instances."""
    db_alias = schema_editor.connection.alias
    for model_name in ['OpenEdXAppServer', 'OpenEdXInstance']:
        model_class = apps.get_model('instance', model_name)
        for instance in model_class.objects.using(db_alias).all():
            callback(instance)


def forwards_github_admin_organizations(apps, schema_editor):
    """Initialize the github_admin_organizations field based on the github_admin_organization_name field."""
    _process_instances(apps, schema_editor, _org_name_to_org_list)


def reverse_github_admin_organizations(apps, schema_editor):
    """Reverse migration."""
    _process_instances(apps, schema_editor, _org_list_to_org_name)


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0057_auto_20160811_1448'),
    ]

    operations = [
        migrations.RunPython(forwards_github_admin_organizations, reverse_github_admin_organizations),
    ]
