# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0058_github_admin_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedxappserver',
            name='github_admin_organization_name',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='github_admin_organization_name',
        ),
    ]
