# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 14:48
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0059_auto_20160811_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='successfully_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
