# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0061_auto_20161028_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancingServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('ssh_username', models.CharField(max_length=32)),
                ('accepts_new_backends', models.BooleanField(default=True)),
                ('fragment_name_postfix', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='load_balancing_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instance.LoadBalancingServer'),
        ),
    ]
