# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0061_auto_20161028_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('port', models.PositiveIntegerField(blank=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('accepts_new_clients', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MongoDB server',
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MySQLServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('port', models.PositiveIntegerField(blank=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('accepts_new_clients', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MySQL server',
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='mongodb_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instance.MongoDBServer'),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='mysql_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instance.MySQLServer'),
        ),
    ]
