# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0063_support_multiple_databases'),
        ('instance', '0062_load_balancer'),
    ]

    operations = [
    ]
