# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0069_openedxappserver_last_activated'),
        ('instance', '0069_managed_rabbitmq'),
    ]

    operations = [
    ]
