# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0071_auto_20170120_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='openstack_server_base_image',
            field=django.contrib.postgres.fields.JSONField(blank=True, default=None, help_text='JSON openstack base image selector, e.g. {"name": "ubuntu-12.04-ref-ul"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='openstack_server_flavor',
            field=django.contrib.postgres.fields.JSONField(blank=True, default=None, help_text='JSON openstack flavor selector, e.g. {"name": "vps-ssd-1"}. Defaults to settings.OPENSTACK_SANDBOX_FLAVOR on server creation.', null=True),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='openstack_server_ssh_keyname',
            field=models.CharField(blank=True, default='', help_text='SSH key name used when setting up access to the openstack project. Defaults to settings.OPENSTACK_SANDBOX_SSH_KEYNAME on server creation.', max_length=256, null=True),
        ),
    ]
