# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0074_openstack_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedxappserver',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='protocol',
        ),
    ]
