# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0075_remove_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Custom tags associated with the instance.', to='instance.InstanceTag'),
        ),
    ]
