# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields.json
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0078_field_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='openstack_server_base_image',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=None, help_text='JSON openstack base image selector, e.g. {"name": "ubuntu-12.04-ref-ul"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='openstack_server_flavor',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=None, help_text='JSON openstack flavor selector, e.g. {"name": "vps-ssd-1"}. Defaults to settings.OPENSTACK_SANDBOX_FLAVOR on server creation.', null=True),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='openstack_server_ssh_keyname',
            field=models.CharField(blank=True, default=None, help_text='SSH key name used when setting up access to the openstack project. Defaults to settings.OPENSTACK_SANDBOX_SSH_KEYNAME on server creation.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='openedxappserver',
            name='openstack_server_base_image',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_BASE_IMAGE',), **{}), help_text='JSON openstack base image selector, e.g. {"name": "ubuntu-12.04-ref-ul"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
        migrations.AlterField(
            model_name='openedxappserver',
            name='openstack_server_flavor',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_FLAVOR',), **{}), help_text='JSON openstack flavor selector, e.g. {"name": "vps-ssd-1"}. Defaults to settings.OPENSTACK_SANDBOX_FLAVOR on server creation.', null=True),
        ),
        migrations.AlterField(
            model_name='openedxappserver',
            name='openstack_server_ssh_keyname',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_SSH_KEYNAME',), **{}), help_text='SSH key name used when setting up access to the openstack project. Defaults to settings.OPENSTACK_SANDBOX_SSH_KEYNAME on server creation.', max_length=256, null=True),
        ),
    ]
