# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0079_openstack_settings_per_appserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancereference',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='When this Instance is no longer needed, it is shut down and marked as archived. Archived instances do not appear in the list of instances, but their data, logs, and settings are preserved (including e.g. all MySQL and MongoDB data).'),
        ),
    ]
