# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0081_is_archived_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openedxappserver',
            options={'ordering': ('-created',), 'verbose_name': 'Open edX App Server'},
        ),
    ]
