# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('instance', '0082_appserver_ordering'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='logentry',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
