# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0084_auto_20170324_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedxappserver',
            name='enable_vm_dns_records',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='enable_vm_dns_records',
        ),
    ]
