# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 03:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0085_auto_20170404_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='additional_monitoring_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts from New Relic Synthetics Monitors when this instance becomes unavailable.', size=None),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='additional_monitoring_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts from New Relic Synthetics Monitors when this instance becomes unavailable.', size=None),
        ),
    ]
