# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0086_auto_20170407_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackserver',
            name='_public_ip',
            field=models.GenericIPAddressField(blank=True, db_column='public_ip', null=True),
        ),
    ]
