# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0087_public_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='external_discovery_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='external_ecommerce_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='internal_discovery_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='internal_ecommerce_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
