# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 13:33
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

def add_internal_discovery_domain(apps, schema_editor):
    """
    Add the internal discovery domain field to each instance.
    """
    prefix = settings.DEFAULT_DISCOVERY_DOMAIN_PREFIX

    OpenEdXInstance = apps.get_model('instance', 'OpenEdXInstance')

    for instance in OpenEdXInstance.objects.all():
        if not instance.internal_discovery_domain:
            instance.internal_discovery_domain = prefix + instance.internal_lms_domain
            instance.save()

def add_internal_ecommerce_domain(apps, schema_editor):
    """
    Add the internal ecommerce domain field to each instance.
    """
    prefix = settings.DEFAULT_ECOMMERCE_DOMAIN_PREFIX

    OpenEdXInstance = apps.get_model('instance', 'OpenEdXInstance')

    for instance in OpenEdXInstance.objects.all():
        if not instance.internal_ecommerce_domain:
            instance.internal_ecommerce_domain = prefix + instance.internal_lms_domain
            instance.save()



class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0088_auto_20170427_1331'),
    ]

    operations = [
        migrations.RunPython(add_internal_discovery_domain),
        migrations.RunPython(add_internal_ecommerce_domain),
    ]
