# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0089_auto_20170427_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='internal_discovery_domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='internal_ecommerce_domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
