# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.mixins.rabbitmq
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0090_auto_20170427_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitMQServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, blank=True)),
                ('description', models.CharField(max_length=250, blank=True)),
                ('api_url', models.URLField(unique=True)),
                ('admin_username', models.CharField(max_length=64)),
                ('admin_password', models.CharField(max_length=128)),
                ('instance_host', models.CharField(max_length=128)),
                ('instance_port', models.PositiveIntegerField(default=5671)),
                ('accepts_new_clients', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RabbitMQ Server',
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='rabbitmq_server',
            field=models.ForeignKey(blank=True, default=instance.models.mixins.rabbitmq.select_random_rabbitmq_server, null=True, on_delete=django.db.models.deletion.PROTECT, to='instance.RabbitMQServer'),
        ),
    ]
