# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0092_rabbitmq_populate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitmqserver',
            name='name',
            field=models.CharField(max_length=250, blank=False),
        ),
    ]
