# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-25 01:08
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0094_watch_sandbox_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxappserver',
            name='openstack_server_base_image',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_BASE_IMAGE',), **{}), help_text='JSON openstack base image selector, e.g. {"name": "xenial-16.04-unmodified"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='openstack_server_base_image',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_BASE_IMAGE',), **{}), help_text='JSON openstack base image selector, e.g. {"name": "xenial-16.04-unmodified"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
    ]
