# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0096_openedxappserver_configuration_theme_settings'),
        ('instance', '0096_load_balancer_configuration_version'),
    ]

    operations = [
    ]
