# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0097_merge_20171102_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='deploy_simpletheme',
            field=models.BooleanField(default=False, help_text='If set to True, new appservers will use theme settings if those are available, e.g. colors and logos chosen in the beta application form; a basic theme will be delpoyed through simple_theme. If set to False, no theme will be created and the default Open edX theme will be used. All instances registered before the theme fields were available should use False if they want to preserve the original theme.', verbose_name='Deploy simple_theme'),
        ),
    ]
