# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0100_decline_new_clients_backends_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancereference',
            name='is_archived',
            field=models.BooleanField(
                default=False,
                help_text='When this Instance is no longer needed, it is shut down and marked as archived. '
                          'Archived instances do not appear in the list of instances, but their data, logs, '
                          'and settings are preserved (including e.g. all MySQL and MongoDB data).<br/>'
                          '<strong>Note: You currently cannot archive an instance from the admin panel. You '
                          'can however un-archive an instance that was already archived.</strong>'
            ),
        ),
    ]
