# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import instance.models.mixins.database


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0101_auto_20180418_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='mongodb_server',
            field=models.ForeignKey(blank=True, default=instance.models.mixins.database.select_random_mongodb_server, null=True, on_delete=django.db.models.deletion.PROTECT, to='instance.MongoDBServer'),
        ),
    ]
