# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0102_add_mongo_replica_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='common_configuration_settings',
            field=models.TextField(blank=True, help_text='YAML variables for commonly needed services.'),
        ),
    ]
