# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0103_openedxappserver_common_configuration_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='storage_type',
            field=models.CharField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('INSTANCE_STORAGE_TYPE',), **{}), max_length=16),
        ),
    ]
