# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0104_openedxinstance_storage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedxappserver',
            name='use_ephemeral_databases',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='use_ephemeral_databases',
        ),
    ]
