# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0106_introduce_instance_ownership_20180821'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='terminated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
