# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-12 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0106_introduce_instance_ownership_20180821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancereference',
            name='creator',
            field=models.ForeignKey(help_text='The user who created the instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='instancereference',
            name='owner',
            field=models.ForeignKey(help_text='The organization that owns the instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Organization'),
        ),
    ]
