# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-01 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0107_openedxappserver_terminated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedxappserver',
            name='github_admin_organizations',
        ),
        migrations.RemoveField(
            model_name='openedxappserver',
            name='github_admin_users',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='github_admin_organizations',
        ),
        migrations.RemoveField(
            model_name='openedxinstance',
            name='github_admin_users',
        ),
    ]
