# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0107_openedxappserver_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='s3_region',
            field=models.CharField(
                blank=True,
                default=functools.partial(instance.models.utils._get_setting, *('AWS_S3_DEFAULT_REGION',), **{}),
                max_length=50
            ),
        ),
    ]
