# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0107_openedxappserver_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='appserver_init_settings',
            field=models.TextField(blank=True, help_text='YAML variables for the appserver-init playbook.'),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='appserver_settings',
            field=models.TextField(blank=True, help_text='YAML variables for the appserver playbook.'),
        ),
    ]
