# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0108_add_appserver_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='celery_broker_transport',
            field=models.CharField(default='amqp', help_text='The Celery broker transport to use.  Supported values include "redis" and "amqp".', max_length=16),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='celery_broker_transport',
            field=models.CharField(default='amqp', help_text='The Celery broker transport to use.  Supported values include "redis" and "amqp".', max_length=16),
        ),
    ]
