# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import instance.models.mixins.secret_keys


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0111_openedxinstance_s3_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='secret_key_rsa_private',
            field=models.TextField(blank=True, default=functools.partial(instance.models.mixins.secret_keys.generate_rsa_key, *(2048,), **{}), help_text='This field holds a RSA private key that is generated when the instance is created, and is used to generate public and private JWK for individual services on each appserver.', verbose_name='Instance-specific private RSA key'),
        ),
    ]
