# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0112_openedxinstance_secret_key_rsa_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='enable_prefix_domains_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
