# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0113_openedxinstance_enable_prefix_domains_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='configuration_playbook_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='configuration_playbook_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
