# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0114_introduce_base_playbook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='privacy_policy_url',
            field=models.URLField(blank=True, default='', help_text='URL to the privacy policy.', verbose_name='URL to Privacy Policy'),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='privacy_policy_url',
            field=models.URLField(blank=True, default='', help_text='URL to the privacy policy.', verbose_name='URL to Privacy Policy'),
        ),
    ]
