# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0115_add_privacy_policy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='extra_custom_domains',
            field=models.TextField(default='', help_text='Add custom domain names, one per line. Domain names must be sub domains of the main LMS domain.'),
            preserve_default=False,
        ),
    ]
