# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-16 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0116_openedxinstance_extra_custom_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='extra_custom_domains',
            field=models.TextField(blank=True, default='', help_text='Add custom domain names, one per line. Domain names must be sub domains of the main LMS domain.'),
        ),
    ]
