# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0117_auto_20190416_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelicAlertCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewRelicAlertPolicy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewRelicEmailNotificationChannel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='newrelicalertpolicy',
            name='email_notification_channels',
            field=models.ManyToManyField(related_name='new_relic_alert_policies', to='instance.NewRelicEmailNotificationChannel'),
        ),
        migrations.AddField(
            model_name='newrelicalertpolicy',
            name='instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_alert_policy', to='instance.OpenEdXInstance'),
        ),
        migrations.AddField(
            model_name='newrelicalertcondition',
            name='alert_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_alert_conditions', to='instance.NewRelicAlertPolicy'),
        ),
        migrations.AddField(
            model_name='newrelicalertcondition',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_alert_conditions', to='instance.NewRelicAvailabilityMonitor'),
        ),
    ]
