# Generated by Django 2.2.4 on 2019-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0118_auto_20190808_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='s3_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
