# Generated by Django 2.2.4 on 2019-10-15 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0119_auto_20191014_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxappserver',
            name='additional_monitoring_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts from New Relic Synthetics Monitors when this instance becomes unavailable, and alerts on AppServer provision failure.', size=None),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='additional_monitoring_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts from New Relic Synthetics Monitors when this instance becomes unavailable, and alerts on AppServer provision failure.', size=None),
        ),
    ]
