# Generated by Django 2.2.6 on 2019-10-24 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0120_auto_20191015_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='provisioning_failure_notification_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts when an AppServer fails to provision.', size=None),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='provisioning_failure_notification_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts when an AppServer fails to provision.', size=None),
        ),
        migrations.AlterField(
            model_name='openedxappserver',
            name='additional_monitoring_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts from New Relic Synthetics Monitors when this instance becomes unavailable.', size=None),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='additional_monitoring_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of additional email addresses other than settings.ADMINS who should receive alerts from New Relic Synthetics Monitors when this instance becomes unavailable.', size=None),
        ),
    ]
