# Generated by Django 2.2.6 on 2019-11-13 12:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import instance.schemas.theming


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0121_update_monitoring_emails_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='theme_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The final theme configuration data committed by the user for deployment. This should be picked up by appservers launched for this instance', null=True, validators=[instance.schemas.theming.theme_schema_validate], verbose_name='Final Theme Configuration JSON'),
        ),
    ]
