# Generated by Django 2.2.6 on 2019-10-23 05:31

import django.contrib.postgres.fields
from django.db import migrations, models
import instance.models.openedx_appserver


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0121_update_monitoring_emails_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='extra_fail_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Optional: A list of extra emails to alert if AppServer fails to provision. Set dynamically by spawn_appserver.', size=None),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='source',
            field=models.CharField(blank=True, choices=[(instance.models.openedx_appserver.Source('api'), 'api'), (instance.models.openedx_appserver.Source('unknown'), 'unknown'), (instance.models.openedx_appserver.Source('watched_pr'), 'watched_pr'), (instance.models.openedx_appserver.Source('registration'), 'registration'), (instance.models.openedx_appserver.Source('instance_redeploy_management_cmd'), 'instance_redeploy_management_cmd')], default='unknown', help_text='A tag to denote where this appserver was spawned from', max_length=100),
        ),
    ]
