# Generated by Django 2.2.10 on 2020-02-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0122_openedxinstance_theme_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelicSSLMonitor',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_ssl_monitors', to='instance.OpenEdXInstance')),
            ],
        ),
        migrations.CreateModel(
            name='NewRelicSSLAlertCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alert_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_ssl_alert_conditions', to='instance.NewRelicAlertPolicy')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_relic_ssl_alert_conditions', to='instance.NewRelicSSLMonitor')),
            ],
        ),
    ]
