# Generated by Django 2.2.10 on 2020-03-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0123_newrelicsslalertcondition_newrelicsslmonitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrelicsslmonitor',
            name='instance',
        ),
        migrations.DeleteModel(
            name='NewRelicSSLAlertCondition',
        ),
        migrations.DeleteModel(
            name='NewRelicSSLMonitor',
        ),
    ]
