# Generated by Django 2.2.10 on 2020-03-24 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import instance.schemas.static_content_overrides


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0124_auto_20200311_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='static_content_overrides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text="The final static content overrides data committed by the user for deployment. This should be picked up the appservers launched for this instance.", null=True, validators=[instance.schemas.static_content_overrides.static_content_overrides_schema_validate], verbose_name='Static content overrides JSON'),
        ),
    ]
