# Generated by Django 2.2.10 on 2020-03-24 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import instance.schemas.static_content_overrides


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0125_openedxinstance_add_static_content_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='configuration_site_configuration_settings',
            field=models.TextField(blank=True, help_text='YAML vars for setting SiteConfiguration variables', null=True),
        ),
    ]
