# Generated by Django 2.2.11 on 2020-05-02 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.deployment


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_move_privacy_policy_subscribe_updates_data'),
        ('instance', '0128_fill_dns_records_updated_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('user', 'Deployment initiated by user'), ('batch', 'Deployment created by batch redeplpoyment script'), ('admin', 'Deployment initiated by Ocim admin user'), ('pr', 'Deployment for GitHub PR'), ('periodic', 'Deployment for periodic build'), ('registration', 'Deployment created during registration'), ('unknown', 'Deployment created unknown or legacy reasons')], default=instance.models.deployment.DeploymentType('Deployment created unknown or legacy reasons'), max_length=10)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.InstanceReference')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='openedx_appserver_count',
            field=models.IntegerField(default=1, help_text='The number of Open edX AppServers to deploy for this instance.'),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='openedx_appserver_count',
            field=models.IntegerField(default=1, help_text='The number of Open edX AppServers to deploy for this instance.'),
        ),
        migrations.CreateModel(
            name='OpenEdXDeployment',
            fields=[
                ('deployment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instance.Deployment')),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Open edX Deployment',
            },
            bases=('instance.deployment',),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instance.Deployment'),
        ),
    ]
