# Generated by Django 2.2.12 on 2020-07-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0131_add_blank_fields_to_appserver_and_deployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancereference',
            name='notes',
        ),
    ]
