# Generated by Django 2.2.12 on 2020-07-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0133_add_notes_attribute_to_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxdeployment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
