# Generated by Django 2.2.12 on 2020-09-28 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0134_openedxdeployment_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='periodic_build_failure_notification_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(), blank=True, default=list, help_text='Optional: Email address where notification must be sent if the build failed', size=None),
        ),
    ]
