# Generated by Django 2.2.12 on 2020-10-09 06:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0135_openedxinstance_periodic_build_failure_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='static_content_display',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='Configure `MKTG_URL_LINK_MAP` to display/hide static pages', null=True),
        ),
    ]
