# Generated by Django 2.2.12 on 2020-11-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0136_openedxinstance_static_content_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openstackserver',
            name='name_prefix',
            field=models.SlugField(max_length=30),
        ),
    ]
