# Generated by Django 2.2.12 on 2020-12-19 19:08

from django.db import migrations, models
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0137_auto_20201112_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxappserver',
            name='ansible_appserver_playbook',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_PLAYBOOK',), **{}), help_text='The path to the common appserver playbook to run on all appservers.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='ansible_appserver_repo_url',
            field=models.URLField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_REPO',), **{}), help_text='The repository to pull the default Ansible playbook from.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='ansible_appserver_requirements_path',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_REQUIREMENTS_PATH',), **{}), help_text='The path to the requirements file for the common appserver playbook.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxappserver',
            name='ansible_appserver_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_VERSION',), **{}), help_text='The version of the Ansible playbook repository to checkout.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='ansible_appserver_playbook',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_PLAYBOOK',), **{}), help_text='The path to the common appserver playbook to run on all appservers.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='ansible_appserver_repo_url',
            field=models.URLField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_REPO',), **{}), help_text='The repository to pull the default Ansible playbook from.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='ansible_appserver_requirements_path',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_REQUIREMENTS_PATH',), **{}), help_text='The path to the requirements file for the common appserver playbook.', max_length=256),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='ansible_appserver_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_VERSION',), **{}), help_text='The version of the Ansible playbook repository to checkout.', max_length=256),
        ),
    ]
