# Generated by Django 2.2.12 on 2021-02-17 12:16

from django.db import migrations, models
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0138_auto_20201219_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxappserver',
            name='ansible_appserver_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_VERSION',), **{}), help_text='The version of the Ansible playbook repository to checkout.', max_length=256),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='ansible_appserver_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('ANSIBLE_APPSERVER_VERSION',), **{}), help_text='The version of the Ansible playbook repository to checkout.', max_length=256),
        ),
    ]
