# Generated by Django 2.2.12 on 2021-03-15 12:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0139_auto_20210217_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxappserver',
            name='openstack_server_base_image',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_BASE_IMAGE',), **{}), help_text='JSON openstack base image selector, e.g. {"name": "focal-20.04-unmodified"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='openstack_server_base_image',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=functools.partial(instance.models.utils._get_setting, *('OPENSTACK_SANDBOX_BASE_IMAGE',), **{}), help_text='JSON openstack base image selector, e.g. {"name": "focal-20.04-unmodified"} Defaults to settings.OPENSTACK_SANDBOX_BASE_IMAGE on server creation.', null=True),
        ),
    ]
