# Generated by Django 2.2.19 on 2021-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0140_update_openstack_base_image_20210315_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancereference',
            name='instance_purpose',
            field=models.CharField(choices=[('0', 'institutional'), ('1', 'proteacher'), ('2', 'sandbox'), ('3', 'development')], default='3', max_length=20),
        ),
    ]
