# Generated by Django 2.2.24 on 2021-08-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0141_features_to_features_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='cache_db',
            field=models.CharField(choices=[('redis', 'redis'), ('rabbit_mq', 'rabbit_mq')], default='rabbit_mq', max_length=9),
        ),
    ]
