# Generated by Django 2.2.23 on 2021-07-01 11:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.mixins.redis
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0141_features_to_features_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('admin_username', models.CharField(max_length=64)),
                ('admin_password', models.CharField(max_length=128)),
                ('instance_host', models.CharField(max_length=128)),
                ('instance_port', models.PositiveIntegerField(default=5671)),
                ('instance_db', models.PositiveIntegerField(default=0)),
                ('use_ssl_connections', models.BooleanField(default=True)),
                ('accepts_new_clients', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Redis Server',
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RedisUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='redis_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='redis_consumer_user',
            field=models.ForeignKey(blank=True, default=instance.models.mixins.redis.new_redis_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_instance', to='instance.RedisUser'),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='redis_server',
            field=models.ForeignKey(blank=True, default=instance.models.mixins.redis.select_random_redis_server, null=True, on_delete=django.db.models.deletion.PROTECT, to='instance.RedisServer'),
        ),
    ]
