# Generated by Django 2.2.24 on 2021-08-13 08:53

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.mixins.redis
import instance.models.utils


def generate_credentials(apps, schema_editor):
    Model = apps.get_model('instance', 'OpenEdXInstance')
    for row in Model.objects.all():
        row.redis_username = instance.models.mixins.redis.random_username()
        row.redis_password = instance.models.mixins.redis.random_password()
        row.save(update_fields=['redis_username', 'redis_password'])



class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0143_add_redis_server'),
    ]

    operations = [
        migrations.RunPython(generate_credentials, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='openedxinstance',
            name='redis_password',
            field=models.CharField(default=instance.models.mixins.redis.random_password, max_length=64),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='redis_username',
            field=models.CharField(default=instance.models.mixins.redis.random_username, max_length=32, unique=True),
        ),
    ]
