# Generated by Django 2.2.24 on 2021-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0144_make_redis_username_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='current_database_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
