# Generated by Django 2.2.24 on 2021-11-22 21:17

from django.db import migrations, models


def set_internal_mfe_domain(apps, schema_editor):
    Model = apps.get_model('instance', 'OpenEdXInstance')
    for row in Model.objects.all():
        # Temp domain for existing instances
        row.internal_mfe_domain = 'app.{}'.format(row.internal_lms_domain)
        row.save(update_fields=['internal_mfe_domain'])


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0144_make_redis_username_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='external_mfe_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='internal_mfe_domain',
            field=models.CharField(blank=True, max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(set_internal_mfe_domain, reverse_code=migrations.RunPython.noop)
    ]
