# Generated by Django 2.2.24 on 2021-12-24 05:30

from django.db import migrations, models

def set_database_name(apps, schema_editor):
    Model = apps.get_model('instance', 'OpenEdXInstance')
    for row in Model.objects.all():
        # Temp domain for existing instances
        row.database_name = row.generate_database_name()
        row.save(update_fields=['database_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0146_make_internal_mfe_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='database_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.RunPython(set_database_name, reverse_code=migrations.RunPython.noop)
    ]
