# Generated by Django 2.2.24 on 2021-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0147_openedxinstance_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='database_name',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
    ]
