# Generated by Django 2.2.24 on 2021-12-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0148_auto_20211224_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='database_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
