# Generated by Django 2.2.24 on 2022-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0149_auto_20211224_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='internal_mfe_domain',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
