# Generated by Django 2.2.24 on 2022-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0150_auto_20220309_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxinstance',
            name='cache_db',
            field=models.CharField(choices=[('redis', 'redis'), ('rabbit_mq', 'rabbit_mq')], default='redis', max_length=9),
        ),
    ]
