# Generated by Django 2.2.24 on 2022-05-18 14:02

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0151_auto_20220529_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedxinstance',
            name='studio_oauth_key',
            field=models.CharField(blank=True, default=functools.partial(django.utils.crypto.get_random_string, *(), **{'allowed_chars': 'abcdefghijklmnopqrstuvwxyz', 'length': 6}), max_length=6),
        ),
        migrations.AddField(
            model_name='openedxinstance',
            name='studio_oauth_secret',
            field=models.CharField(blank=True, default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 32}), max_length=32),
        ),
    ]
