# Generated by Django 2.2.24 on 2022-06-03 12:49

from django.db import migrations, models
import functools
import instance.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0152_studio_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedxappserver',
            name='configuration_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('DEFAULT_CONFIGURATION_VERSION',), **{}), max_length=256),
        ),
        migrations.AlterField(
            model_name='openedxinstance',
            name='configuration_version',
            field=models.CharField(default=functools.partial(instance.models.utils._get_setting, *('DEFAULT_CONFIGURATION_VERSION',), **{}), max_length=256),
        ),
    ]
