# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import instance.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0002_timestampedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('github_handle', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(instance.models.utils.ValidateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Organization'),
        ),
    ]
