# Generated by Django 2.2.6 on 2019-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_introduce_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accept_paid_support',
            field=models.BooleanField(default=False, help_text='User understands that they may email OpenCraft for support, and that such emails are subject to hourly fees.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accepted_privacy_policy',
            field=models.DateTimeField(blank=True, help_text='Date the user accepted the privacy policy.', null=True, verbose_name='Accept privacy policy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_to_updates',
            field=models.BooleanField(default=False, help_text='I want OpenCraft to keep me updated about important news, tips, and new features, and occasionally send me an email about it.'),
        ),
    ]
