# Generated by Django 2.2.6 on 2019-11-12 08:44

from django.db import migrations


def migrate_data_to_userprofile(apps, schema_editor):
    BetaTestApplication = apps.get_model('registration', 'BetaTestApplication')
    for application in BetaTestApplication.objects.all():
        application.user.profile.accepted_privacy_policy = application.accepted_privacy_policy
        application.user.profile.subscribe_to_updates = application.subscribe_to_updates
        application.user.profile.save()


def migrate_data_to_betatestapplication(apps, schema_editor):
    BetaTestApplication = apps.get_model('registration', 'BetaTestApplication')
    for application in BetaTestApplication.objects.all():
        application.accepted_privacy_policy = application.user.profile.accepted_privacy_policy
        application.subscribe_to_updates = application.user.profile.subscribe_to_updates
        application.save()


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0004_auto_20191112_0838'),
        ('registration', '0011_betatestapplication_privacy_policy_url'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_to_userprofile, migrate_data_to_betatestapplication
        )
    ]
