# Generated by Django 2.2.12 on 2020-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_move_privacy_policy_subscribe_updates_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accept_domain_condition',
            field=models.BooleanField(default=False, help_text='User asserts that they have the rights to use to registered domain.'),
        ),
    ]
