# Generated by Django 2.2.12 on 2020-10-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_accept_custom_domain_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accept_paid_support',
        ),
    ]
