---
# Playbook to remove the stale load balancer fragments

- hosts: all
  become: True
  vars:
    HOURS_OLDER_THAN: 8
    FRAGMENT_DIR: /etc/haproxy/conf.d
    FRAGMENT_PATTERN: "integration*"
    REMOVE_FRAGMENTS: false
  tasks:
    - name: Find load balancer fragment files older than "{{ HOURS_OLDER_THAN }}" hours
      find:
        paths: "{{ FRAGMENT_DIR }}"
        age: "{{ HOURS_OLDER_THAN }}h"
        patterns: "{{ FRAGMENT_PATTERN }}"
      register: stale_fragment_files

    - name: Debug print the stale fragment files found
      debug:
        msg: "Found '{{ item.path }}'"
      with_items: "{{ stale_fragment_files.files }}"

    - name: Remove the stale fragment files
      command: >
        haproxy-config remove "{{ item.path.split("/")[-1] }}"
      with_items: "{{ stale_fragment_files.files }}"
      when: REMOVE_FRAGMENTS
